### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by b0l3nk** [simon816/PHPDeobfuscator#20]
PHP Fatal error:  Uncaught Exception: Block BdPpQ_While_17_If_18 is alias! in /root/PHPDeobfuscator/src/ControlFlowVisitor.php:425
Stack trace:
#0 /root/PHPDeobfuscator/src/ControlFlowVisitor.php(312): PHPDeobfuscator\CodeBlock->checkAlias()
#1 /root/PHPDeobfuscator/src/ControlFlowVisitor.php(350): PHPDeobfuscator\CodeBlock->rebuild()
#2 [internal function]: PHPDeobfuscator\CodeBlock->processNode()
#3 /root/PHPDeobfuscator/src/ControlFlowVisitor.php(331): array_map()
#4 /root/PHPDeobfuscator/src/ControlFlowVisitor.php(350): PHPDeobfuscator\CodeBlock->rebuild()
#5 [internal function]: PHPDeobfuscator\CodeBlock->processNode()
#6 /root/PHPDeobfuscator/src/ControlFlowVisitor.php(331): array_map()
#7 /root/PHPDeobfuscator/src/ControlFlowVisitor.php(324): PHPDeobfuscator\CodeBlock->rebuild()
#8 /root/PHPDeobfuscator/src/ControlFlowVisitor.php(324): PHPDeobfuscator\CodeBlock->rebuild()
#9 /root/PHPDeobfuscator/src/ControlFlowVisitor.php(324): PHPDeobfuscator\CodeBlock->rebuild()
#10 /root/PHPDeobfuscator/src/ControlFlowVisitor.php(32 in /root/PHPDeobfuscator/src/ControlFlowVisitor.php on line 425

**Comment by simon816** [comment]
Are you able to share the code sample with me to investigate this?

**Comment by b0l3nk** [comment]
https://pastebin.com/g1d4bwg8

**Comment by simon816** [comment]
It seems that is a private link as I can't view it. Could you try again or email it to me? (me@simon816.com)

**Comment by b0l3nk** [comment]
I have sent the sample code

**Comment by simon816** [comment]
Thanks.

I have reduced the sample to this minimal code that triggers the bug

```php
<?php 
while (true) {
    label:
}
```

**Comment by b0l3nk** [comment]
Thank you very much, there are no more errors.
And it can be decoded
